/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alocamentoreserva;

import conexao.ConexaoException;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ReservaBuscarPainel extends javax.swing.JPanel {
    List<Reserva> reservas = new ArrayList<>();
    ReservaDAO reservaDAO = new ReservaDAO();
    /**
     * Creates new form VendaBuscarData
     */
    public ReservaBuscarPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservaTable = new javax.swing.JTable();

        pesquisarBt.setText("Buscar");
        pesquisarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtActionPerformed(evt);
            }
        });

        reservaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ambiente", "Professor", "Data e hora inicial", "Data e hora final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reservaTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(reservaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pesquisarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pesquisarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBtActionPerformed
        // TODO add your handling code here:
        try {
            reservas = reservaDAO.findAll();

            DefaultTableModel model = (DefaultTableModel) reservaTable.getModel();
            model.setRowCount(0);

            for(Reserva reserva : reservas){
                model.addRow(new Object[]{
                        reserva.id,
                        reserva.ambiente.codigo,
                        reserva.professor.nome,
                        reserva.dataHorarioIni,
                        reserva.dataHorarioFim
                        // senha está hashada, não faz sentido
                        // além disso o que importa
                        // é que o administrador possa alterar
                        // a senha, não necessariamente conhecer ela
//                        guarda.senha
                });
            } 
        } catch (ConexaoException ex) {
            Logger.getLogger(ReservaBuscarPainel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarBtActionPerformed

    private void abrirJanela(JFrame jframe){
//        double x = this.getLocationOnScreen().getX();
//        double y = this.getLocationOnScreen().getY();
//        double dx = this.getSize().getWidth();
//        double dy = this.getSize().getHeight();
//        double xx = x + (dx / 2);
//        double yy = y + (dy / 2);
//        double dxx = jframe.getSize().getWidth() / 2;
//        double dyy = jframe.getSize().getHeight() / 2;
//        
//        jframe.setLocation(new Point((int) xx - (int) dxx, (int) yy - (int) dyy));
        
        jframe.setLocationRelativeTo(null);
        jframe.setVisible(true);
        jframe.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void reservaTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservaTableMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            System.out.println("entrou");
            
            int linhaSlc = reservaTable.getSelectedRow();
            
            Reserva.selecionada = reservas.get(linhaSlc);
            ( new JanelaWrapper() ).setVisible(true);
            
//                abrirJanela(new VendaDetalhesJanela(this, gerenciador, vendas.get(linhaSlc)));
//
        }
    }//GEN-LAST:event_reservaTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarBt;
    private javax.swing.JTable reservaTable;
    // End of variables declaration//GEN-END:variables
}
